# Esta es la segunda parte del ETL en donde terminamos de realizar la limpieza y transformaciones hasta quedarnos con el último DataFrame de Yelp a partir del cual vamos a trabajar.

In [3]:
import pandas as pd
import datetime as dt
import demoji
import re
from datetime import datetime
from IPython.display import display

# Cargar
df_yelp= pd.read_csv('C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness2.csv')
# Seleccionar columnas
df_yelp= df_yelp[['review_id', 'user_id', 'business_id', 'stars_y','text', 'date']]
#Elimina nulos que tenga la columna text
df_yelp.dropna(subset='text', inplace=True)
# yo no eliminé duplicados porque el archivo q me pasó fede no tenían
df_yelp.duplicated().sum()

#Cambiar a formato fecha , se crean 3 columnas con el año, mes y día
df_yelp['date'] = df_yelp['date'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
df_yelp['anio'] = df_yelp['date'].dt.year
df_yelp['mes'] = df_yelp['date'].dt.month
df_yelp['dia']=df_yelp['date'].dt.day
df_yelp=df_yelp.drop(['date'],axis=1)

#Selección de 2017 a 2021
df_yelp=df_yelp[df_yelp['anio']>=2017]

#Limpieza de datos, todas a minúsculas, se quitan emojis y signos de puntuación
df_yelp['text'] = df_yelp['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df_yelp['text']= df_yelp['text'].apply(lambda x: demoji.replace(x, ''))
df_yelp['text']=df_yelp['text'].apply(lambda x: x.lower() if x is not None else '')
df_yelp

# Save the cleaned DataFrame to a CSV file
df_yelp.to_csv('YelpReviewBusinessLimpio.csv', index=False)

# Display the DataFrame
display(df_yelp)

,review_id,user_id,business_id,stars_y,text,anio,mes,dia
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,if you decide to eat here just be aware it is ...,2018,7,7
1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,this is the second time we tried turning point...,2017,5,13
2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,the place is cute and the staff was very frien...,2017,8,8
3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,we came on a saturday morning after waiting a ...,2017,11,19
4,M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,mediocre at best the decor is very nice and i ...,2017,9,9
...,...,...,...,...,...,...,...,...
4265989,BGSe6tne3hZXyB_DRf-tBg,ObZnTiwMA-4gaTqa1_mB6A,wsPBZXcq28mUE9B-CkdY8Q,4.5,this bar is definitely geared for its shriner ...,2022,1,8
4265990,REZ0pf6mAphzyolfTgfXKQ,YKVydQ6nZ3CsvSko8X8qTA,0vksR9cowkTN_xL-sdZnNw,4.0,the restaurant at the cheshire is average at b...,2021,12,31
4265991,YqkQOAxnG7jYs9m68Pm2FQ,VzuYiWOWg7RxJ9kEGw6ecA,LJkF_qtlpmTDZXMmjUr7xw,5.0,very attentive and checked in via text wheneve...,2022,1,9
4265992,pPqcyyKyg3AruEOuhUPAJw,BIZt3IwVH66S0_UbMEh2MA,HaSEQCVzuVuMtJD_vVlfVg,3.5,walked into this gas station and walked right ...,2021,1,2
4265993,Pi4sofBVDX_1FkiKG5ft5g,zQSW0_fi46U_066lo88GXQ,ujsFpiiGu92nUsjlFc9pew,1.0,i only come to this location because the parki...,2020,1,15

In [1]:
import pandas as pd
import datetime as dt
import demoji
import re
from datetime import datetime
from IPython.display import display

# Cargar
df_yelp = pd.read_csv('C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness2.csv')

# Seleccionar columnas
selected_columns = ['review_id', 'user_id', 'business_id', 'stars_y', 'text', 'date']
df_yelp = df_yelp[selected_columns]

# Elimina nulos en la columna 'text'
df_yelp.dropna(subset=['text'], inplace=True)

# Cambiar a formato fecha, creando columnas para año, mes y día
df_yelp['date'] = pd.to_datetime(df_yelp['date'])
df_yelp['anio'] = df_yelp['date'].dt.year
df_yelp['mes'] = df_yelp['date'].dt.month
df_yelp['dia'] = df_yelp['date'].dt.day
df_yelp.drop(['date'], axis=1, inplace=True)

# Selección de registros desde 2017 hasta 2021
df_yelp = df_yelp[df_yelp['anio'] >= 2017]

# Limpieza de datos en la columna 'text': a minúsculas, eliminar emojis y signos de puntuación
df_yelp['text'] = df_yelp['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df_yelp['text'] = df_yelp['text'].apply(lambda x: demoji.replace(x, ''))
df_yelp['text'] = df_yelp['text'].str.lower()

# Guardar el DataFrame limpio en un archivo CSV sin index
df_yelp.to_csv('YelpReviewBusinessLimpio.csv', index=False)

# Mostrar el DataFrame
display(df_yelp)

,review_id,user_id,business_id,stars_y,text,anio,mes,dia
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,if you decide to eat here just be aware it is ...,2018,7,7
1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,this is the second time we tried turning point...,2017,5,13
2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,the place is cute and the staff was very frien...,2017,8,8
3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,we came on a saturday morning after waiting a ...,2017,11,19
4,M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,mediocre at best the decor is very nice and i ...,2017,9,9
...,...,...,...,...,...,...,...,...
4265989,BGSe6tne3hZXyB_DRf-tBg,ObZnTiwMA-4gaTqa1_mB6A,wsPBZXcq28mUE9B-CkdY8Q,4.5,this bar is definitely geared for its shriner ...,2022,1,8
4265990,REZ0pf6mAphzyolfTgfXKQ,YKVydQ6nZ3CsvSko8X8qTA,0vksR9cowkTN_xL-sdZnNw,4.0,the restaurant at the cheshire is average at b...,2021,12,31
4265991,YqkQOAxnG7jYs9m68Pm2FQ,VzuYiWOWg7RxJ9kEGw6ecA,LJkF_qtlpmTDZXMmjUr7xw,5.0,very attentive and checked in via text wheneve...,2022,1,9
4265992,pPqcyyKyg3AruEOuhUPAJw,BIZt3IwVH66S0_UbMEh2MA,HaSEQCVzuVuMtJD_vVlfVg,3.5,walked into this gas station and walked right ...,2021,1,2
4265993,Pi4sofBVDX_1FkiKG5ft5g,zQSW0_fi46U_066lo88GXQ,ujsFpiiGu92nUsjlFc9pew,1.0,i only come to this location because the parki...,2020,1,15

In [2]:
import pandas as pd
import datetime as dt
import demoji
import re
from datetime import datetime
from IPython.display import display

# Cargar
df_yelp = pd.read_csv('C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness2.csv')

# Seleccionar columnas que deseas mantener
selected_columns = ['name', 'city', 'state', 'review_count', 'attributes', 'categories', 'review_id', 'user_id', 'business_id', 'stars_y', 'text', 'date']
df_yelp = df_yelp[selected_columns]

# Elimina nulos en la columna 'text'
df_yelp.dropna(subset=['text'], inplace=True)

# Cambiar a formato fecha, creando columnas para año, mes y día
df_yelp['date'] = pd.to_datetime(df_yelp['date'])
df_yelp['anio'] = df_yelp['date'].dt.year
df_yelp['mes'] = df_yelp['date'].dt.month
df_yelp['dia'] = df_yelp['date'].dt.day
df_yelp.drop(['date'], axis=1, inplace=True)

# Selección de registros desde 2017 hasta 2021
df_yelp = df_yelp[df_yelp['anio'] >= 2017]

# Limpieza de datos en la columna 'text': a minúsculas, eliminar emojis y signos de puntuación
df_yelp['text'] = df_yelp['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df_yelp['text'] = df_yelp['text'].apply(lambda x: demoji.replace(x, ''))
df_yelp['text'] = df_yelp['text'].str.lower()

# Guardar el DataFrame limpio en un archivo CSV sin index
df_yelp.to_csv('YelpReviewBusinessLimpio.csv', index=False)

# Mostrar el DataFrame
display(df_yelp)

,name,city,state,review_count,attributes,categories,review_id,user_id,business_id,stars_y,text,anio,mes,dia
0,Turning Point of North Wales,North Wales,PA,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,if you decide to eat here just be aware it is ...,2018,7,7
1,Turning Point of North Wales,North Wales,PA,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,this is the second time we tried turning point...,2017,5,13
2,Turning Point of North Wales,North Wales,PA,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,the place is cute and the staff was very frien...,2017,8,8
3,Turning Point of North Wales,North Wales,PA,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,we came on a saturday morning after waiting a ...,2017,11,19
4,Turning Point of North Wales,North Wales,PA,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,mediocre at best the decor is very nice and i ...,2017,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265989,El Korah Oasis,Boise,TN,7,"{'GoodForDancing': 'False', 'NoiseLevel': ""'qu...","Nightlife, Dive Bars, Arts & Entertainment, Ba...",BGSe6tne3hZXyB_DRf-tBg,ObZnTiwMA-4gaTqa1_mB6A,wsPBZXcq28mUE9B-CkdY8Q,4.5,this bar is definitely geared for its shriner ...,2022,1,8
4265990,The Restaurant at The Cheshire,Saint Louis,TN,80,"{'NoiseLevel': ""u'average'"", 'RestaurantsDeliv...","Restaurants, American (New), British",REZ0pf6mAphzyolfTgfXKQ,YKVydQ6nZ3CsvSko8X8qTA,0vksR9cowkTN_xL-sdZnNw,4.0,the restaurant at the cheshire is average at b...,2021,12,31
4265991,Food Lion,Smyrna,IN,5,"{'BikeParking': 'False', 'BusinessAcceptsCredi...","Grocery, Food",YqkQOAxnG7jYs9m68Pm2FQ,VzuYiWOWg7RxJ9kEGw6ecA,LJkF_qtlpmTDZXMmjUr7xw,5.0,very attentive and checked in via text wheneve...,2022,1,9
4265992,Circle K,Tucson,FL,7,"{'BusinessParking': ""{'garage': False, 'street...","Food, Gas Stations, Automotive, Grocery, Conve...",pPqcyyKyg3AruEOuhUPAJw,BIZt3IwVH66S0_UbMEh2MA,HaSEQCVzuVuMtJD_vVlfVg,3.5,walked into this gas station and walked right ...,2021,1,2
4265993,Quest Diagnostics,Philadelphia,NV,5,{'ByAppointmentOnly': 'False'},"Health & Medical, Diagnostic Services, Medical...",Pi4sofBVDX_1FkiKG5ft5g,zQSW0_fi46U_066lo88GXQ,ujsFpiiGu92nUsjlFc9pew,1.0,i only come to this location because the parki...,2020,1,15